version: '1.0'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env.heroku

  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: