version: '1.0'

services:
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8070 --insecure --noreload
    volumes:
      - .:/code
    ports:
      - "8070:8070"
    depends_on:
      - redis
    env_file:
      - .env.docker

  redis:
    image: redis/redis-stack-server
#    command: redis-server --appendonly yes
#    command: redis-server --protected-mode no CONFIG SET protected-mode no
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:15-bullseye
    container_name: edsite-db
    #    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8071:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env.docker
#    networks:
#      - edsite-network

volumes:
  redis_data: