version: '0.1'

services:
#  db:
#    image: postgres
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000 --insecure
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    env_file:
#      - .env.dev

  redis:
    image: redis/redis-stack-server
#    command: redis-server --appendonly yes
#    command: redis-server --protected-mode no CONFIG SET protected-mode no
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: