version: '1.0'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env.docker

  redis:
    image: redis/redis-stack-server
#    command: redis-server --appendonly yes
#    command: redis-server --protected-mode no CONFIG SET protected-mode no
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: