# Generated by Django 4.0.6 on 2022-09-16 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("average_price", models.IntegerField()),
                ("game_id", models.IntegerField(db_index=True, unique=True)),
                ("tradedangerous_id", models.IntegerField(db_index=True, unique=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="CommodityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tradedangerous_id", models.IntegerField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("pos_x", models.FloatField()),
                ("pos_y", models.FloatField()),
                ("pos_z", models.FloatField()),
                ("tradedangerous_id", models.IntegerField(db_index=True, unique=True)),
            ],
            options={
                "ordering": ["-id"],
                "index_together": {("pos_x", "pos_y", "pos_z")},
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ls_from_star", models.IntegerField()),
                ("pad_size", models.CharField(max_length=1)),
                ("item_count", models.IntegerField()),
                ("modified", models.DateTimeField(null=True)),
                ("market", models.BooleanField()),
                ("black_market", models.BooleanField()),
                ("shipyard", models.BooleanField()),
                ("outfitting", models.BooleanField()),
                ("rearm", models.BooleanField()),
                ("refuel", models.BooleanField()),
                ("repair", models.BooleanField()),
                ("planetary", models.BooleanField()),
                ("fleet", models.BooleanField()),
                ("odyssey", models.BooleanField()),
                (
                    "tradedangerous_id",
                    models.IntegerField(db_index=True, null=True, unique=True),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="EDSite.system",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Rare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cost", models.IntegerField()),
                ("max_alloc", models.IntegerField()),
                ("illegal", models.BooleanField()),
                ("suppressed", models.BooleanField()),
                ("tradedangerous_id", models.IntegerField(db_index=True, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rares",
                        to="EDSite.commoditycategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiveListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity_tradedangerous_id", models.IntegerField()),
                ("station_tradedangerous_id", models.IntegerField(db_index=True)),
                ("demand_price", models.IntegerField()),
                ("demand_units", models.IntegerField()),
                ("supply_price", models.IntegerField()),
                ("supply_units", models.IntegerField()),
                ("modified", models.DateTimeField()),
                ("from_live", models.BooleanField()),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="EDSite.commodity",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="EDSite.station",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="commodity",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commodities",
                to="EDSite.commoditycategory",
            ),
        ),
        migrations.CreateModel(
            name="CarrierMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode", models.CharField(max_length=1)),
                ("carrier_name", models.CharField(max_length=128)),
                ("units", models.IntegerField()),
                ("worker_profit", models.IntegerField()),
                ("active", models.BooleanField()),
                ("date_posted", models.DateTimeField()),
                ("date_completed", models.DateTimeField(null=True)),
                (
                    "carrier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="missions",
                        to="EDSite.station",
                    ),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="EDSite.commodity",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="EDSite.station",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("demand_price", models.IntegerField()),
                ("demand_units", models.IntegerField()),
                ("supply_price", models.IntegerField()),
                ("supply_units", models.IntegerField()),
                ("datetime", models.DateTimeField()),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historic_listings",
                        to="EDSite.commodity",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historic_listings",
                        to="EDSite.station",
                    ),
                ),
            ],
            options={
                "index_together": {("commodity_id", "station_id")},
            },
        ),
    ]
