# Generated by Django 4.0.6 on 2022-09-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EDSite", "0002_remove_station_item_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livelisting",
            name="station_tradedangerous_id",
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
