# Generated by Django 4.0.6 on 2022-07-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0002_rename_profit_carriermission_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carriermission',
            old_name='price',
            new_name='worker_profit',
        ),
    ]
