# Generated by Django 4.0.6 on 2022-07-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0003_rename_price_carriermission_worker_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriermission',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
