# Generated by Django 4.0.6 on 2022-07-31 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0004_alter_carriermission_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='carriermission',
            name='carrier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='EDSite.station'),
        ),
        migrations.AddField(
            model_name='carriermission',
            name='carrier_name',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
