# Generated by Django 4.0.6 on 2022-09-22 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0004_faction_government_state_superpower_localfaction_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='system',
            index_together=set(),
        ),
    ]
