# Generated by Django 4.0.6 on 2022-08-01 15:57

from django.db import migrations
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0005_carriermission_carrier_carriermission_carrier_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_price', models.IntegerField()),
                ('demand_units', models.IntegerField()),
                ('demand_level', models.IntegerField()),
                ('supply_price', models.IntegerField()),
                ('supply_units', models.IntegerField()),
                ('supply_level', models.IntegerField()),
                ('modified', models.DateTimeField()),
                ('from_live', models.BooleanField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings',
                                                to='EDSite.commodity')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings',
                                              to='EDSite.station')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),

        migrations.AlterIndexTogether(
            name='livelisting',
            index_together={('commodity_id', 'station_id')},
        ),
        migrations.AlterIndexTogether(
            name='historiclisting',
            index_together={('commodity_id', 'station_id')},
        ),
    ]
