# Generated by Django 4.0.6 on 2022-09-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0005_alter_system_index_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localfaction',
            old_name='last_update',
            new_name='modified',
        ),
    ]
