# Generated by Django 4.0.6 on 2022-09-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0006_rename_last_update_localfaction_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='tradedangerous_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
