# Generated by Django 4.0.6 on 2022-08-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0006_alter_livelisting_index_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livelisting',
            name='demand_level',
        ),
        migrations.RemoveField(
            model_name='livelisting',
            name='supply_level',
        ),
    ]
