# Generated by Django 4.0.6 on 2022-09-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0007_faction_tradedangerous_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='home_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factions', to='EDSite.system'),
        ),
        migrations.AddField(
            model_name='station',
            name='population',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='population',
            field=models.IntegerField(null=True),
        ),
    ]
