# Generated by Django 4.0.6 on 2022-08-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0007_remove_livelisting_demand_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiclisting',
            name='demand_level',
        ),
        migrations.RemoveField(
            model_name='historiclisting',
            name='supply_level',
        ),
    ]
