# Generated by Django 4.0.6 on 2022-08-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0008_remove_historiclisting_demand_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livelisting',
            name='commodity_tradedangerous_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livelisting',
            name='station_tradedangerous_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
