# Generated by Django 4.0.6 on 2022-09-23 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0009_system_allegiance_system_government'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='home_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factions', to='EDSite.system'),
        ),
        migrations.AlterField(
            model_name='system',
            name='allegiance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems', to='EDSite.superpower'),
        ),
        migrations.AlterField(
            model_name='system',
            name='controlling_faction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls', to='EDSite.faction'),
        ),
        migrations.AlterField(
            model_name='system',
            name='government',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems', to='EDSite.government'),
        ),
    ]
