# Generated by Django 4.0.6 on 2022-08-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0009_livelisting_commodity_tradedangerous_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='data_age_days',
        ),
        migrations.AddField(
            model_name='station',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
