# Generated by Django 4.0.6 on 2022-09-04 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0010_remove_station_data_age_days_station_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiclisting',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historic_listings', to='EDSite.station'),
        ),
    ]
