# Generated by Django 4.0.6 on 2022-09-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0010_alter_faction_home_system_alter_system_allegiance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='population',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='population',
            field=models.BigIntegerField(null=True),
        ),
    ]
