# Generated by Django 4.0.6 on 2022-09-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0011_alter_station_population_alter_system_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='population',
        ),
    ]
