# Generated by Django 4.0.6 on 2022-09-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0011_alter_historiclisting_station'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='livelisting',
            index_together=set(),
        ),
    ]
