# Generated by Django 4.0.6 on 2022-09-23 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0012_remove_station_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='allegiance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factions', to='EDSite.superpower'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='government',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factions', to='EDSite.government'),
        ),
    ]
