# Generated by Django 4.0.6 on 2022-09-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0012_alter_livelisting_index_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['-id']},
        ),
    ]
