# Generated by Django 4.0.6 on 2022-09-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0013_alter_faction_allegiance_alter_faction_government'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Famine'), (2, 'Bust'), (3, 'None'), (4, 'Boom'), (5, 'Investment')], max_length=100)),
            ],
        ),
    ]
