# Generated by Django 4.0.6 on 2022-09-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0014_economystate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Lockdown'), (2, 'Civil Unrest'), (3, 'None'), (4, 'Civil Liberty')], max_length=100)),
            ],
        ),
    ]
