# Generated by Django 4.0.6 on 2022-09-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0015_securitystate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecurityState',
        ),
    ]
