# Generated by Django 4.0.6 on 2022-09-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0019_systemsecurity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecurityState',
        ),
        migrations.DeleteModel(
            name='SystemSecurity',
        ),
    ]
