# Generated by Django 4.0.6 on 2022-09-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0020_delete_securitystate_delete_systemsecurity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='security',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Anarchy'), (5, 'Lawless')], null=True),
        ),
    ]
