# Generated by Django 4.0.6 on 2022-09-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0021_alter_system_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='allegiance',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Empire'), (2, 'Independent'), (3, 'Alliance'), (4, 'Federation')], null=True),
        ),
        migrations.AlterField(
            model_name='superpower',
            name='name',
            field=models.CharField(choices=[(1, 'Empire'), (2, 'Independent'), (3, 'Alliance'), (4, 'Federation')], max_length=100),
        ),
    ]
