# Generated by Django 4.0.6 on 2022-09-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0022_alter_faction_allegiance_alter_superpower_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='allegiance',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Empire'), (2, 'Independent'), (3, 'Alliance'), (4, 'Federation')], null=True),
        ),
        migrations.DeleteModel(
            name='Superpower',
        ),
    ]
