# Generated by Django 4.0.6 on 2022-09-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0023_alter_system_allegiance_delete_superpower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='government',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Anarchy'), (2, 'Communism'), (3, 'Confederacy'), (4, 'Cooperative'), (5, 'Corporate'), (6, 'Democracy'), (7, 'Dictatorship'), (8, 'Feudal'), (9, 'Patronage'), (10, 'Prison Colony'), (11, 'Theocracy')], null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='government',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Anarchy'), (2, 'Communism'), (3, 'Confederacy'), (4, 'Cooperative'), (5, 'Corporate'), (6, 'Democracy'), (7, 'Dictatorship'), (8, 'Feudal'), (9, 'Patronage'), (10, 'Prison Colony'), (11, 'Theocracy')], null=True),
        ),
        migrations.DeleteModel(
            name='Government',
        ),
    ]
