# Generated by Django 4.0.6 on 2022-09-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0024_alter_faction_government_alter_system_government_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EconomyState',
        ),
    ]
