# Generated by Django 4.0.6 on 2022-09-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0025_delete_economystate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localfaction',
            name='happiness',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Despondent'), (2, 'Unhappy'), (3, 'Discontented'), (4, 'Happy'), (5, 'Elated')], null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(choices=[(1, 'Incursion'), (2, 'Infested'), (3, 'Blight'), (4, 'Drought'), (5, 'Outbreak'), (6, 'infrastructure Failure'), (7, 'Natural Disaster'), (8, 'Revolution'), (9, 'Cold War'), (10, 'Trade War'), (11, 'Pirate Attack'), (12, 'Terrorist Attack'), (13, 'Public Holiday'), (14, 'Technological Leap'), (15, 'Historic Event'), (16, 'Colonisation'), (17, 'War'), (18, 'Civil War'), (19, 'Election'), (20, 'Retreat'), (21, 'Expansion'), (22, 'None'), (101, 'Famine'), (102, 'Bust'), (104, 'Boom'), (105, 'Investment'), (201, 'Lockdown'), (202, 'Civil Unrest'), (204, 'Civil Liberty')], max_length=100),
        ),
    ]
