# Generated by Django 4.0.6 on 2022-09-26 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EDSite', '0026_alter_localfaction_happiness_alter_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localfaction',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_factions', to='EDSite.system'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(choices=[(1, 'Incursion'), (2, 'Infested'), (3, 'Blight'), (4, 'Drought'), (5, 'Outbreak'), (6, 'infrastructure Failure'), (7, 'Natural Disaster'), (8, 'Revolution'), (9, 'Cold War'), (10, 'Trade War'), (11, 'Pirate Attack'), (12, 'Terrorism'), (13, 'Public Holiday'), (14, 'Technological Leap'), (15, 'Historic Event'), (16, 'Colonisation'), (17, 'War'), (18, 'Civil War'), (19, 'Election'), (20, 'Retreat'), (21, 'Expansion'), (22, 'None'), (101, 'Famine'), (102, 'Bust'), (104, 'Boom'), (105, 'Investment'), (201, 'Lockdown'), (202, 'Civil Unrest'), (204, 'Civil Liberty')], max_length=100),
        ),
    ]
